[package]
name = "osm_routes"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
geo = "0.29.3"
geojson = { git = "https://github.com/georust/geojson", features = ["geo-types"] }
osm-reader = { git = "https://github.com/a-b-street/osm-reader" }
